-- Adminer 4.2.5 MySQL dump

SET NAMES utf8;
SET time_zone = '+00:00';
SET foreign_key_checks = 0;
SET sql_mode = 'NO_AUTO_VALUE_ON_ZERO';

DROP TABLE IF EXISTS `beers`;
CREATE TABLE `beers` (
  `id` int(21) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `brewery` varchar(255) NOT NULL,
  `abv` float NOT NULL DEFAULT '0',
  `description` text NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `beers` (`id`, `name`, `brewery`, `abv`, `description`) VALUES
(1,	'Ekstra',	'Švyturys',	5.2,	'Dortmunder/European Export klasės lageris, kurio receptą 1995 metais sukūrė „Švyturio“ vyriausioji aludarė Džuljeta Armonienė. Tai – pirmasis Lietuvos alus, sulaukęs tarptautinio pripažinimo ir apdovanotas Pasaulio alaus taurės Aukso ir Sidabro medaliais bei Stokholmo alaus festivalio Aukso medaliu'),
(2,	'J. W. Reincke',	'Švyturys',	5,	'Alus, nusipelnęs „Švyturio“ pirmtako, pirmojo Klaipėdos alaus bravoro įkūrėjo vardo.\r\n \r\nŠio lagerio alaus skonyje ir aromate dominuoja salyklas, o poskonyje jaučiamas lengvas apynių kartumas. Išskirtinis skaidrus ir lengvas, šviesios gintaro spalvos, žemutinės fermentacijos alus, subrandintas šaltyje 0,568 l (pintos) skardinėse.'),
(3,	'Baltas',	'Švyturys',	5,	'Kvietinis Hefeweizen stiliaus alus, Tradicinės „Švyturio“ kolekcijos narys. Jis pasižymi gaiviu skoniu ir aromatu, kuris primena gvazdikėlių, bananų, slyvų, apelsinų žievelių ir egzotinių vaisių puokštę. Nefiltruotą, drumstą, savito skonio, ypatingo aromato alų rekomenduojama pagardinti citrinos griežinėliu ir gerti iš specialios atšaldytos taurės.'),
(4,	'Baltijos',	'Švyturys',	5.8,	'Tamsusis Märzen/ Oktoberfest lageris, Tradicinės „Švyturio“ kolekcijos alus, verdamas nuo 1965 m. Etnografai įsitikinę, jog šis „kovo“ stiliaus alus savo spalva ir skoniu artimiausias pirmajam „Švyturio“ alui, 1784 m. pasiūlytam alaus daryklos įkūrėjo vokiečių pirklio Rainkės.'),
(5,	'Ekstra Draught',	'Švyturys',	5.2,	'tai legendinis „Švyturio“ šviesusis lager alus, kuris prieš išpilstant yra ne pasterizuojamas, o mikrofiltruojamas, todėl išlieka gyvas – toks, kaip bare. Aukso spalvos alus iš Tradicinės „Švyturio“ kolekcijos išsiskiria tiršta balta puta, harmoningu aromatu, turtingu, švelniu, ilgai išliekančiu skoniu, kurį pagyvina vos juntamas apynių kartumas. Daugelio tyrimų duomenimis, šis aukščiausios kokybės alaus kategorijai priskiriamas alus yra mėgstamiausias Lietuvoje.'),
(6,	'Memelbräu',	'Švyturys',	5.3,	'tai brown ale stiliaus alus, išsiskiriantis maloniai sausu kiek rūgštoku skoniu su derančiu karamelės poskoniu. Šis alus verdamas naudojant net trijų rūšių salyklą: miežinį, kvietinį ir karamelinį. „Švyturio“ rūsių horizontalios talpyklos suteikia „Memelbräu“ minėtą savitą skonį ir aromatą.'),
(7,	'20 statinių',	'Švyturys',	7.9,	'naujasis Tradicinės „Švyturio“ kolekcijos narys, pirmasis Lietuvoje ąžuolinėse škotiško viskio statinėse subrandintas stautas.\r\n \r\nMažytėje Ailos saloje Škotijoje esančioje distilerijoje nuo 1881 metų gaminamas „Bunnahabhain“ viskis. Būtent šis salyklinis viskis 18 metų brendo šiose statinėse. Statinių sienelės įsigėrė medaus, riešutų, jūros aromato su vyšnių ir ąžuolo tonais. Šį sykį, tik išpilsčius subrandintą viskį į butelius, statinės iš Škotijos buvo atplukdytos tiesiai į Klaipėdos uostą.\r\n \r\n﻿„20 statinių“ - 3 mėnesius brandintas, ypatingas trijų skirtingų salyklų ir degintų miežių stautas, kurio pagaminome vos 20 statinių. Švelniai salstelėjęs, medaus, riešutų bei vyšnių skonio tonais pasižymintis alus laukia jūsų gurmaniško įvertinimo. Rekomenduojama ragauti iš vyno taurės.'),
(8,	'Švyturio',	'Švyturys',	5,	'5,0 % stiprumo lengvas, vaiskios aukso spalvos ir švelnaus apynių aromato alus, kuriame subtiliai dera sodrus skonis ir kartokas apynių gaivumas. Šis ypač švelnaus skonio alus pagamintas iš salyklo, apynių, aromatinių apynių, alaus mielių ir gėlo vandens.'),
(9,	'Gintarinis',	'Švyturys',	4.6,	'tai lengvas Pilsner klasės, šviesaus gintaro spalvos alus, gaminamas iš Pilzeno klasės salyklo, karčiųjų apynių, alaus mielių ir gėlo vandens. Lietuvos alaus mėgėjai jį vertina dėl gaivaus, lengvo skonio ir švelnaus apynių aromato.'),
(10,	'Stipriausias',	'Švyturys',	7.5,	'tai German-Style Bock tipo šviesus, stiprus, sodraus aukso spalvos alus, pagamintas iš salyklo, apynių, alaus mielių ir gėlo vandens. Jis išsiskiria saldoku skoniu ir įvairių gėlinių augalų aromatu. „Stipriausias“, užsienio rinkose dar žinomas kaip „Švyturys Maximum“, skirtas tiems alaus mėgėjams, kurie mėgsta itin sodrų ir stiprų skonį.'),
(11,	'Tradicinis',	'Švyturys',	6,	'alus brendo kartu su šio alaus mėgėjais. Atsižvelgiant į vartotojų tyrimuose išsakytus poreikius, šis Maibock stiliaus alus yra stipresnis, skaisčios gintaro spalvos, šiek tiek salstelėjęs, įgijęs išraiškingą salyklo skonį su švelniai juntamu karčiųjų apynių atspalviu.'),
(12,	'Nealkoholinis',	'Švyturys',	0,	'alus kuriamas laikantis tos pačios technologijos, kaip ir gaminant įprastas alaus rūšys, tik alaus gamybos pabaigoje jame esantis alkoholis pašalinamas dializės metodu. Tai lengvo, švelnaus skonio ir aromato, labai gaivus, su sodria puta nealkoholinis alus, skirtas tiems, kas nori tikro alaus skonio, tačiau nesiruošia daryti jokių kompromisų dėl savo gyvensenos.'),
(13,	'Radler Raspberry',	'Utenos alus',	2,	'Lietuvoje pamėgtą „Utenos Radler“ kolekciją papildo aviečių skonis. Alaus kokteilyje išlaikėme lengvumą ir vaisiškumą, kad tiktų vasarai. Jo skonyje pajusi dominuojančią avietę, tačiau po uogų saldumo gomurį pakutens įmaišytos citrinos sultys.'),
(14,	'Utenos Kriek',	'Utenos alus',	4.6,	'Pristatome vyšnių skonio tamsųjį „Kriek“ stiliaus  alų, kuris pirmą kartą buvo pagamintas Belgijoje. „Utenos Kriek“ skonyje noksta šeivamedžio uogos, o aromate juntami vaisiai. Alaus saldumą papildo ir subalansuoja švelnus apynių kartumas.'),
(15,	'Žalia Balta',	'Utenos alus',	5,	'Specialiai pasauliniam „Žalgirio“ fanų surašymui užsakėme naują alų – „Žalia Balta“.\r\n\r\nAlaus skonis – šiek tiek kartėlesnis, nes mes alaus neužkandame tortais ir eklerais. Jo žalią pavadinimą liudija ir aromatingi apyniai, o jo karamelinis salyklas atsispindi spalvoje ir skonyje.\r\n\r\nKas kartą pirkdamas šį alų pildai „Žalgirio“ komandos biudžetą!'),
(16,	'Dark',	'Utenos alus',	4.5,	'Jis sugrįžo atnaujintu skoniu ir išvaizda. Šio alaus tamsume pajausi švelnų karamelinį salyklo skonį, o aromate pažinsi irisinius saldainius. Solidusis „Utenos Dark“ – vidutinio kartumo alus, kuriame subtiliai skleidžiasi saldumas.'),
(17,	'Bocmano Ūsai',	'Raudonų plytų alaus dirbtuvės/Švyturys',	6,	'Tai alus, kuris sakantiems „man visas alus per kartus“ turėtų duoti suprasti, ką iš tikro reiškia kartus alus. Tai IPA (angl. India pale ale), šis alaus stilius yra būtent apie apynius ir kartumą. Verdant šį alų, dideliais kiekiais į katilą krito apyniai, kurie suteikė ne tik kartumo, bet vaisišką` skonį ir aromatą – tai, kas būdinga būtent šiems amerikietiškiems apyniams. Kad būtume tikri, kad apynių nepritrūks, jų dedame ir brandindami šį alų. Nesaikingas apynių naudojimas yra tam, kad alus turėtų aromatus, nuo kokių bocmanui susiraito ūsai. '),
(18,	'Ungurio kojos',	'Raudonų plytų alaus dirbtuvės/Švyturys',	5.3,	'Taip, tai lager alus, kokį dabar ypač mėgsta užjūrio craft alaus gerbėjai: su trupučiu karamelinio salyklo, suteikiančio sodresnę spalvą, bei lengvu Millennium ir Cascade apynių akcentu. Cascade yra etaloninė JAV apynių rūšis – be jos dabar veikiausiai neapsieina nė viena eksperimentuojanti darykla. Šių apynių dedame į alų brandinimo metu. Rezultatas – sesijinis alus su ryškiu juodųjų serbentų aromatu. Kitoks, bet negąsdinantis. Kaip ungurys, žingsniuojantis per molą'),
(19,	'Bėganti kopa',	'Raudonų plytų alaus dirbtuvės/Švyturys',	4.5,	'Mes mėgstame kvietinį alų ir žinome, kad jis gali būti labai skirtingas. Šįkart – tai mūsų improvizacija belgiško kvietinio alaus tema. Įprastinis kviečių ir miežių salyklų santykis (60:40) suteikia alui tvirtą putą ir šviesią, lyg saulės nutviekstos kopos, spalvą. Dėkui Doemens kvietinio alaus mielėms už aromatą, bet čia juk belgiškas alus, taigi keturių ingredientų neužteks. Tad virimo pabaigoje į katilą tradiciškai beriame kalendrų sėklų, saldžiųjų apelsinų žievelių ir ne visai tradiciškai – patraiškytų kardamonų. Nepamirškite pauostyti prieš kiekvieną gurkšnį. '),
(20,	'Nežinomas krantas',	'Raudonų plytų alaus dirbtuvės/Švyturys',	6,	'Šaltuoju metų laiku vienuoliai į alų deda daugiau salyklo. „Įdėkime daugiau ir mes, – pagalvojome, – o tada dar ko nors.“ Virdami šį alų naudojame belgiškus Cara Aroma, Munich II, Cara Munich, Pilsner salyklus. Bet tai dar ne viskas – alų brandiname su kiek paskrudintomis prancūziško ąžuolo drožlėmis, suteikiančiomis skonio, kokio kartais turi ąžuolo statinėje brandintas vynas. Tai naujas krantas skonių jūroje. Už sudėtingumą!'),
(21,	'Ryklio kavinukas',	'Raudonų plytų alaus dirbtuvės/Švyturys',	4.5,	'4 skirtingi salyklai ir laktozė užtikrina, kad alui netrūks tamsių kavos ir šokolado aromatų, saldumo ir klampumo. O kad to nebūtų maža, alų brandiname su Kolumbijos Medeljino regione auginta ir \"Crooked nose & coffee stories\" Vilniuje lengvai skrudinta kava. '),
(22,	'Zombis tundroje',	'Raudonų plytų alaus dirbtuvės/Švyturys',	6.6,	'Raudonas ir drūtas elis, kurį tokį padaro „Pilsner“ ir „Carared“ salyklai, o „Simcoe“ apyniai papildo aromatais. Ribota partija, kurią virėme per pilnatį, tad alaus yra tiek ir tik tiek, nė buteliu daugiau. Tai alus iš idėjos. ');

-- 2016-10-03 20:30:40
